version: "3.8"

services:

  server:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/interview
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data: